export const TRANSLATIONS_EN = {
    step0_title:"Welcome to SxpSwap!",
    step0_subtitle: "This tool is designed to facilitate the swap (migration) from SXP ERC20 and SXP BEP20 to SXP Mainnet. Click on the FAQ below to learn more about this tool. Otherwise click next to start migrating your tokens to mainnet.",
    useful_links: "Useful links to check before starting the migration.",
    faq: "Frequently Asked Questions",
    telegram: "Solar Community on Telegram",
    ready_to_swap: "Ready to swap? Click next!",
    download_wallet: "Before you can start the swap. You are required to create a mainnet Solar (SXP) wallet. Click on the link below to create a wallet.",
    download_wallet_button: "Download Solar SXP wallet",
    next: "Next",
    previous: "Previous",
    step1_title: "Where do you have your SXP?",
    step1_subtitle: "Select the blockchain in which you hold your Swipe (SXP) tokens.",
    synchronizing: "Synchronizing with MetaMask...",
    install_metamask: "Please install Metamask.",
    metamask_unavailable: "MetaMask not available",
    connecting: "Connecting...",
    not_connected: "Not connected",
    connect_metamask: "Connect to Metamask",
    step2_title: "Enter SXP amount.",
    step2_subtitle: "Enter the amount of Swipe (SXP) tokens you wish to swap. You don't have to swap all at once on your first try.",
    you_have: "You currently have {{amount}} SXP", // intended for "you currently have x SXP"
    swap_all: "swap all", // always in lowercase
    step3_title: "What is your mainnet SXP address?",
    step3_subtitle: "Enter your SXP mainnet address where you will receive your SXP tokens.",
    enter_address: "Enter a valid SXP mainnet address",
    not_valid_address: "This is not a valid SXP mainnet address.",
    valid_address: "This is a valid SXP mainnet address.",
    step4_title: "Swap your SXP!",
    step4_subtitle: "Click on the approve button, wait until you can swap... yes, do that!",
    gonna_swap: "You are going to swap",
    to: "to",
    approve_swap: "Approve swap",
    approving_swap: "Approving swap...",
    swap_now: "Swap now",
    swapping: "Sending swap transaction...",
    wait_for_sxp: "It may take a few minutes before you see your mainnet SXP in your Solar Mainnet Wallet.",
    step5_title: "You just swapped {{amount}} SXP!",
    step5_subtitle: "",
    you_still_have: "You still have {{balance}} of SXP to swap. We hope you swap them soon!",
    swap_more: "Swap more",
    see_transaction: "You can see the transaction:",
    click_here: "click here"
   };
