export const TRANSLATIONS_IT = {
    step0_title:"Benvenuto su SxpSwap!",
    step0_subtitle: "Questo strumento è progettato per facilitare lo scambio (migrazione) da SXP ERC20 e SXP BEP20 a SXP Mainnet. Clicca sulle FAQ qui sotto per saperne di più su questo strumento. Altrimenti clicca su Avanti per iniziare a migrare i tuoi token su mainnet.",
    useful_links: "Link utili da controllare prima di iniziare la migrazione.",
    faq: "Domande frequenti",
    telegram: "Solar Community su Telegram",
    ready_to_swap: "Pronto a scambiare? Clicca avanti!",
    download_wallet: "Prima di iniziare lo scambio, è necessario creare un wallet Solar (SXP) mainnet. Clicca sul link qui sotto per creare un wallet.",
    download_wallet_button: "Scarica Solar SXP wallet",
    next: "Avanti",
    previous: "Indietro",
    step1_title: "Dove sono i tuoi SXP?",
    step1_subtitle: "Seleziona la blockchain in cui detieni i tuoi token Swipe (SXP).",
    synchronizing: "Sincronizzazione con MetaMask...",
    install_metamask: "Si prega di installare Metamask.",
    metamask_unavailable: "MetaMask non disponibile",
    connecting: "Connessione...",
    not_connected: "Non connesso",
    connect_metamask: "Connetti a Metamask",
    step2_title: "Inserisci importo in SXP.",
    step2_subtitle: "Inserisci la quantità di token Swipe (SXP) che vuoi scambiare. Non è necessario scambiare tutto in una volta al primo tentativo.",
    you_have: "Attualmente hai {{amount}} SXP", // intended for "you currently have x SXP"
    swap_all: "scambia tutto", // always in lowercase
    step3_title: "Qual è il tuo indirizzo SXP mainnet?",
    step3_subtitle: "Inserisci il tuo indirizzo SXP mainnet dove riceverai i tuoi token SXP.",
    enter_address: "Inserisci un indirizzo SXP mainnet valido",
    not_valid_address: "Questo non è un indirizzo SXP mainnet valido.",
    valid_address: "Questo indirizzo SXP mainnet è valido.",
    step4_title: "Scambia i tuoi SXP!",
    step4_subtitle: "Clicca sul pulsante di approvazione, attendi di poter scambiare... sì, fallo!",
    gonna_swap: "Stai per scambiare",
    to: "per",
    approve_swap: "Approva scambio",
    approving_swap: "Scambio in approvazione...",
    swap_now: "Scambia ora",
    swapping: "Invio della transazione di scambio in corso...",
    wait_for_sxp: "Potrebbero essere necessari alcuni minuti prima che tu veda i tuoi SXP mainnet nel tuo wallet Solar mainnet.",
    step5_title: "Hai appena scambiato {{amount}} SXP!",
    step5_subtitle: "",
    you_still_have: "Hai ancora {{balance}} SXP da scambiare. Ci auguriamo li scambierai presto!",
    swap_more: "Scambia ancora",
    see_transaction: "Puoi vedere la transazione:",
    click_here: "clicca qui"
   };
