export const TRANSLATIONS_KR = {
    step0_title:"SxpSwap에 오신 것을 환영합니다!",
    step0_subtitle: "이 도구은 SXP ERC20 및 SXP BEP20에서 SXP 메인넷으로의 거래(마이그레이션)를 용이하게 만들도록 설계되었습니다. 이 도구에 대한 자세한 내용을 보려면 아래 FAQ를 클릭하십시오. 아니면 다음을 클릭하여 토큰을 메인넷으로 마이그레이션하십시오.",
    useful_links: "이것은 마이그레이션을 시작하기 전 확인할 수 있는 유용한 링크입니다.",
    faq: "자주 하는 질문(FAQ)",
    telegram: "Telegram의 솔라 커뮤니티",
    ready_to_swap: "교환 준비가 되셨습니까? 다음을 클릭하세요!",
    download_wallet: "교환을 시작하기 전 메인넷 솔라(SXP) 지갑을 생성해야 합니다. 지갑을 생성하려면 아래 링크를 클릭해 주세요.",
    download_wallet_button: "솔라 SXP 지갑 다운로드",
    next: "다음",
    previous: "기존",
    step1_title: "여러분의 SXP는 어디에 있습니까?",
    step1_subtitle: "여러분의 SXP 토큰을 보유하고 있는 블록체인을 선택하십시오.",
    synchronizing: "메타마스크와 동기화하는 중...",
    install_metamask: "메타마스크를 설치해주세요.",
    metamask_unavailable: "메타마스크를 사용할 수 없습니다",
    connecting: "접속 중...",
    not_connected: "접속되지 않았습니다.",
    connect_metamask: "메타마스크에 접속",
    step2_title: "SXP 금액을 입력하세요..",
    step2_subtitle: "교환하려는 SXP 토큰의 양을 입력하세요. 첫 시도에서 한꺼번에 모두 교환할 필요는 없습니다..",
    you_have: "귀하는 현재 {{amount}} SXP를 보유하고 있습니다.", // "현재 x SXP를 보유하고 있습니다."
    swap_all: "모두 교환", // 항상 소문자
    step3_title: "귀하의 메인넷 SXP 주소는 무엇입니까?",
    step3_subtitle: "SXP 토큰을 받을 SXP 메인넷 주소를 입력하세요.",
    enter_address: "유효한 SXP 메인넷 주소를 입력하세요",
    not_valid_address: "유효한 SXP 메인넷 주소가 아닙니다.",
    valid_address: "유효한 SXP 메인넷 주소입니다.",
    step4_title: "귀하의 SXP를 교환하세요!",
    step4_subtitle: "승인 버튼을 클릭하고 교환될 때까지 기다려 주세요... 네, 그렇게 하세요!",
    gonna_swap: "귀하의 토큰은 곧 교환될 예정입니다",
    to: "...에로",
    approve_swap: "교환 승인",
    approving_swap: "교환을 승인하는 중...",
    swap_now: "지금 교환",
    swapping: "교환 거래를 전송하는 중...",
    wait_for_sxp: "솔라 메인넷 지갑에서 메인넷 SXP를 확인하는 데 몇 분이 걸릴 수 있습니다.",
    step5_title: "방금 {{amount}} SXP를 교환했습니다!",
    step5_subtitle: "",
    you_still_have: "교환할 SXP의 {{잔액}}ㅇ가 아직 남아 있습니다. 곧 교환하시기 바랍니다!",
    swap_more: "더 많은 교환",
    see_transaction: "다음과 같은 거래를 볼 수 있습니다.",
    click_here: "여기를 클릭하세요"
   };
