export const TRANSLATIONS_EN = {
    step0_title:"Bun venit la SxpSwap!",
    step0_subtitle: "Acest website faciliteaza migrarea (schimbul) SXP ERC20 sau SXP BEP20 catre SXP Mainnet. Click mai jos pe Intrebari Frecvente pentru a citi mai multe despre acest proces sau click pe butonul Inainte pentru a incepe migrarea catre Mainnet",
    useful_links: "Useful links to check before starting the migration.",
    faq: "Intrebari Frecvente",
    telegram: "Comunitatea Solar pe Telegram",
    ready_to_swap: "Esti pregatit sa faci schimbul? Click pe butonul Inainte!",
    download_wallet: "Inainte de a face schimbul ai nevoie de un portofel SXP. Iti poti face un portofel dand click mai jos.",
    download_wallet_button: "Descarca portofelul Solar SXP",
    next: "Inainte",
    previous: "Inapoi",
    step1_title: "De unde facem migrarea SXP?",
    step1_subtitle: "Alege blockchain-ul unde ai acum tokenuri Swipe (SXP).",
    synchronizing: "Sincronizare cu MetaMask...",
    install_metamask: "Instaleaza Metamask.",
    metamask_unavailable: "MetaMask nu este disponibil",
    connecting: "Conectare...",
    not_connected: "Deconectat",
    connect_metamask: "Conectat la Metamask",
    step2_title: "Enter SXP amount.",
    step2_subtitle: "Introdu suma Swipe (SXP) pe care doresti sa o schimbi. Nu trebuie sa-i schimbi pe toti la prima incercare.",
    you_have: "Acum ai {{amount}} SXP", // intended for "you currently have x SXP"
    swap_all: "schimba tot", // always in lowercase
    step3_title: "SXP ?",
    step3_subtitle: "Introdu adresa SXP mainnet unde doresti sa se faca schimbul.",
    enter_address: "Introdu o adresa valida SXP mainnet",
    not_valid_address: "Acesta nu este un portofel valid SXP mainnet.",
    valid_address: "Aceasta este un portofel valid SXP mainnet.",
    step4_title: "Schimba SXP!",
    step4_subtitle: "Click pe butonul Aproba schimbul si asteapta finalizarea procesului de aprobare.  wait until you can swap... yes, do that!",
    gonna_swap: "You are going to swap",
    to: "catre",
    approve_swap: "Aproba schimbul",
    approving_swap: "Aprobare schimb...",
    swap_now: "Schimba acum",
    swapping: "Transmitere tranzactie scrhimb...",
    wait_for_sxp: "Poate dura cateva minute pana cand tranzactia va fi vizibila in portofelul mainnet SXP",
    step5_title: "Doar ce ai schimbat {{amount}} SXP!",
    step5_subtitle: "",
    you_still_have: "Inca mai ai {{balance}} SXP disponibili pentru schimb. We hope you swap them soon!",
    swap_more: "Schimba mai mult",
    see_transaction: "Poti vedea tranzactia:",
    click_here: "click aici"
   };
