export const TRANSLATIONS_TR = {
    step0_title:"SxpSwap’e hoşgeldin!",
    step0_subtitle: "Bu araç, SXP ERC20 ve SXP BEP20’den SXP Ana Ağı’na takası(taşımayı) kolaylaştırmak için tasarlanmıştır. Bu araç hakkında daha fazla bilgi almak için SSS’a tıklayın. Ya da tokenlarınızı ana ağa taşımaya başlamak için sonrakiye tıklayın.",
    useful_links: "Taşımaya başlamadan önce göz atabileceğiniz yararlı linkler.",
    faq: "Sıkça Sorulan Sorular",
    telegram: "Telegram’da Solar Topluluğu",
    ready_to_swap: "Takasa hazır mısın? Sonrakine tıkla!",
    download_wallet: "Takas etmeden önce. Ana ağ Solar (SXP) cüzdanı oluşturmanız gerekiyor. Cüzdan oluşturmak için aşağıdaki linke tıkla.",
    download_wallet_button: "Solar SXP cüzdanı indir",
    next: "Sonraki",
    previous: "Önceki",
    step1_title: "SXP’n nerede?",
    step1_subtitle: "SXP tokenlerinizi tutmak istediğiniz blockchain’i seçin.",
    synchronizing: "MetaMask ile senkronize ediliyor...",
    install_metamask: "Lütfen Metamask indirin.",
    metamask_unavailable: "MetaMask mevcut değil",
    connecting: "Bağlanıyor...",
    not_connected: "Bağlı değil",
    connect_metamask: "Metamask’e bağlan",
    step2_title: "SXP miktarını girin.",
    step2_subtitle: "Takas etmek istediğiniz SXP token miktarını girin. İlk denemenizde hepsini birden takas etmeniz gerekmiyor.",
    you_have: "Şu anda {{amount}} adet SXP’n var", // intended for "you currently have x SXP"
    swap_all: "hepsini takas et", // always in lowercase
    step3_title: "SXP ana ağ adresiniz ne?",
    step3_subtitle: "SXP tokenlerini alacağınız SXP ana ağ adresinizi girin.",
    enter_address: "Geçerli bir SXP ana ağ adresi girin",
    not_valid_address: "Bu, geçerli bir SXP ana ağ adresi değil.",
    valid_address: "Bu, geçerli bir SXP ana ağ adresi.",
    step4_title: "SXP’ni takas et!",
    step4_subtitle: "Onayla butonuna basın, takas edene kadar bekleyin…evet, aynen öyle!",
    gonna_swap: "Burayla takas yapacaksın",
    to: ":",
    approve_swap: "Takası onayla",
    approving_swap: "Takas onaylanıyor…",
    swap_now: "Şimdi takas et",
    swapping: "Takas işlemi gönderiliyor.",
    wait_for_sxp: "Solar Ana Ağ Cüzdanı’nınızda ana ağ SXP’nizi görmeniz bir kaç dakikayı bulabilir.",
    step5_title: "{{amount}} adet SXP takas ettin!",
    step5_subtitle: "",
    you_still_have: "Takas için hala {{balance}} adet SXP’n var. Umarız yakın zamanda onları da takas edersin!",
    swap_more: "Daha fazla takas yap",
    see_transaction: "Alım satım işlemini görebilirsin:",
    click_here: "buraya tıkla"
   };
