export const TRANSLATIONS_VN = {
    step0_title:"Xin chào đến với SxpSwap!",
    step0_subtitle: "Công cụ này được thiết kế để tạo hỗ trợ việc hoán đổi (di chuyển) từ SXP ERC20 và SXP BEP20 sang SXP Mainnet. Nhấp vào Câu hỏi thường gặp bên dưới để tìm hiểu thêm về công cụ này. Nếu không, hãy nhấp vào tiếp theo để bắt đầu chuyển đổi SXP sang mainnet. ",
    useful_links: "Những link hữu ích cần biết trước khi chuyển đổi..",
    faq: "Những câu hỏi thường gặp",
    telegram: "Cộng đồng Solar ở Telegram",
    ready_to_swap: "Sẵn sàng chuyển đổi? Nhấp vào đây!",
    download_wallet: "Trước khi bắt đầu chuyển đổi. Bạn bắt buộc phải tạo ví mainnet Solar (SXP). Nhấp vào liên kết bên dưới để tạo ví.",
    download_wallet_button: "Tải ví Solar SXP",
    next: "Tiếp theo",
    previous: "Quay lại",
    step1_title: "Bạn đang để SXP ở đâu?",
    step1_subtitle: "Lựa chọn blockchain nơi bạn đang giữ SXP dưới đây.",
    synchronizing: "Đang đồng bộ với MetaMask...",
    install_metamask: "Hãy cài đặt Metamask.",
    metamask_unavailable: "MetaMask không tồn tại",
    connecting: "Đang kết nối...",
    not_connected: "Chưa kết nối",
    connect_metamask: "Kết nối với Metamask",
    step2_title: "Nhập số lượng SXP.",
    step2_subtitle: "Nhập số lượng Swipe (SXP) bạn muốn chuyển đổi. Bạn không nhất thiết phải chuyển đổi tất cả trong một lần.",
    you_have: "Bạn đang có {{amount}} SXP", // intended for "you currently have x SXP"
    swap_all: "chuyển tất cả", // always in lowercase
    step3_title: "Địa chỉ ví mainnet SXP của bạn?",
    step3_subtitle: "Nhập địa chỉ ví SXP mainnet bạn sẽ nhận SXP sau khi chuyển đổi.",
    enter_address: "Nhập chính xác một địa chỉ SXP mainnet",
    not_valid_address: "Đây không phải là một địa chỉ SXP mainnet.",
    valid_address: "Đây đúng là địa chỉ SXP mainnet.",
    step4_title: "Chuyển đổi SXP!",
    step4_subtitle: "Nhấp vào nút xác nhận, và chờ đợi!",
    gonna_swap: "Bạn đang bắt đầu chuyển đổi",
    to: "đến",
    approve_swap: "Xác nhận chuyển đổi",
    approving_swap: "Đang xác nhận chuyển đổi...",
    swap_now: "Chuyển đổi ngay",
    swapping: "Đang gửi giao dịch chuyển đổi...",
    wait_for_sxp: "Có thể mất vài phút để bạn thấy mainnet SXP trong ví Solar Mainnet.",
    step5_title: "Bạn vừa chuyển đổi {{amount}} SXP!",
    step5_subtitle: "",
    you_still_have: "Bạn vẫn còn {{balance}} SXP để chuyển đổi. Chúng tôi hy vọng bạn sẽ chuyển đổi sớm!",
    swap_more: "Chuyển đổi thêm",
    see_transaction: "Bạn có thể xem giao dịch:",
    click_here: "nhấp vào đây"
   };
